### ISSUE TITLE
Missing protobuf file

### ISSUE THREAD

**Issue by mnzaki** [ez-connect/strapi-hugo-webhook#2]
Thank you for this work! I would really like to use this package but it seems the protobuf file is not committed, or I'm missing something??

Also I can't figure out what the `gkgen` command is from, any tips?

**Comment by vnhdx** [comment]
@mnzaki  The gRPC protocol is dropped in the [v0.4.0](https://github.com/ez-connect/strapi-hugo-webhook/tree/v0.4.0) - WIP. I will let you know once it is done.

**Comment by vnhdx** [comment]
Sorry about keeping it for so long. Please check the [v0.4](https://github.com/ez-connect/strapi-hugo-webhook/tree/v0.4) version.

**Comment by mnzaki** [comment]
Thank you for supporting this project, I'm excited to try it out soon! I wish to use this setup for my personal website :)

**Comment by vnhdx** [comment]
See the example [here](https://github.com/ez-connect/hugo-theme/blob/v0.4/Dockerfile) for setting up the webook for your site. You can update the `templates`  to fit with your data or use the default one.
